export const RESET_STATE = 'RESET_STATE';

export const REQUEST_LOADING = 'REQUEST_LOADING';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';

export const FAVOR = 'FAVOR';
export const DISFAVOR = 'DISFAVOR';

export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
